// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace EmployeePass.iOS
{
	public partial class AirportListViewController : UIViewController
	{
		public AirportListViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
