// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace EmployeePass.iOS
{
	public partial class CheckInfoViewController : UIViewController
	{
		public Route SelectedRoute { get; set; }

		public CheckInfoViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();


			lbEndAirport.Text = $"{SelectedRoute.StopAirport.Name} {SelectedRoute.StopAirport.IATA_Code}";
			lbStartAirport.Text = $"{SelectedRoute.StartAirport.Name} {SelectedRoute.StartAirport.IATA_Code}";
			lbStartTerminalEnglish.Text = SelectedRoute.StartTerminal.EnglishName;
			lbStartTerminalName.Text = SelectedRoute.StartTerminal.EnglishName;
			lbStartTerminalNote.Text = SelectedRoute.StartTerminal.Note;
			lbStartTerminalPhone.Text = SelectedRoute.StartTerminal.Phone;
			lbStartTerminalWeb.Text = SelectedRoute.StartTerminal.Web;
		}
	}
}
