// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace EmployeePass.iOS
{
	public partial class FlightCellView : UITableViewCell
	{
		public FlightCellView (IntPtr handle) : base (handle)
		{
		}

		public void UpdateUIWith(Flight flight){
			lbFlightId.Text = flight.Id;
			lbStartAirport.Text =  $"{flight.FlightRoute.StartAirport.Name} {flight.FlightRoute.StartAirport.IATA_Code}";
			lbStopAirport.Text = $"{flight.FlightRoute.StopAirport.Name} {flight.FlightRoute.StopAirport.IATA_Code}";
		}
	}
}
