// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using Debug = System.Diagnostics.Debug ;

namespace EmployeePass.iOS
{
	public partial class LoginViewController : UIViewController
	{
		public LoginViewController (IntPtr handle) : base (handle)
		{
		}

		#region View's Lifecycle

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			btnLogin.TouchUpInside += (object sender, EventArgs e) => {

				AppDelegate.AppUser = new Employee{Name = @"Liddle Fang"};

				InvokeOnMainThread(()=>{
					PerformSegue( "moveToMenuViewSegue", this);
				});

			};
		}

		#endregion

		#region Touches' Event

		public override void TouchesBegan (Foundation.NSSet touches, UIEvent evt)
		{
			base.TouchesBegan (touches, evt);

			var touch = touches.AnyObject as UITouch;

			Debug.WriteLine ( $"TapCount:{touch.TapCount}" );
		}

		public override void TouchesMoved (Foundation.NSSet touches, UIEvent evt)
		{
			base.TouchesMoved (touches, evt);

			var touch = touches.AnyObject as UITouch;

			//var pointOfButton = touch.PreviousLocationInView (this.btnLogin);
			var pointOfView = touch.LocationInView (this.View);

			Debug.WriteLine ( $"X:{pointOfView.X}, Y:{pointOfView.Y}"   ); 

		}

		public override void TouchesEnded (Foundation.NSSet touches, UIEvent evt)
		{
			base.TouchesEnded (touches, evt);

			Debug.WriteLine ( @"TouchesEnded" );
		}

		#endregion
	}
}
