// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace EmployeePass.iOS
{
	public partial class PassDetailCellView : UITableViewCell
	{
		public PassDetailCellView (IntPtr handle) : base (handle)
		{
		}

		public void UploadTicket(Ticket ticket){
			lbRoute.Text = $"{ticket.TicketFlight.FlightRoute.StartAirport.IATA_Code} - {ticket.TicketFlight.FlightRoute.StopAirport.IATA_Code}";
			lbClass.Text = ticket.ClassName;
			lbDate.Text = ticket.StartDate.ToString ("d");
		}
	}
}
