// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace EmployeePass.iOS
{
	public partial class PassCellView : UITableViewCell
	{
		public PassCellView (IntPtr handle) : base (handle)
		{
		}

		public void UploadPass(EmployeeElectronicPass pass){
			lbRoute.Text = pass.FlightsToString;
			lbApplyId.Text = pass.ProcessId;
			lbPassId.Text = pass.ElectronicPassId;
			lbDate.Text = pass.AppliedDate.ToString ("d");
		}
	}
}
